import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Header from "@/src/compositions/Header";
import UI from "@/src/compositions/UI";
import News from "@/src/compositions/News";
import Footer from "@/src/compositions/Footer";
import { api } from "@/src/api/datoApi";
import ReduxProvider from "@/src/redux/ReduxProvider";

const bebas_neue = Bebas_Neue({
  variable: "--font-bebas_neue",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = await api.get.navigation("sv");
  const settings = await api.get.settings("sv");
  console.log("nav", navigation);
  console.log("settings", settings);

  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${bebas_neue.variable}  antialiased`}>
          <Header />

          {children}

          <Footer settings={settings} />
        </body>
      </html>
    </ReduxProvider>
  );
}
